### ISSUE TITLE
Only displays a black window when ran (Vulkan Errors with 'vkQueuePresentKHR' and 'vkAcquireNextImageKHR')

### ISSUE THREAD

**Issue by SixHourHalfLife** [vinegarhq/sober#107]
### Acknowledgement of checking existent issues

- [X] I have checked if my issue has already been reported, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

I'm under the impression that this is an nvidia driver bug, but I was hoping someone could point me in the right direction.

After initial setup, whenever I try to run Sober using `flatpak run org.vinegarhq.Sober` (with or without specifying a URI), only a black window appears. I'm on a hybrid graphics nvidia system running EndeavourOS and I was running into the same issue as [#95](https://github.com/vinegarhq/sober/issues/95), which was also resolved by disabling the wayland socket for Sober. However, I'm still unable to get any graphical output out of Sober post-initial setup.

I noticed that the log files contained a bunch of lines with 'VULKAN ERROR: vkAcquireNextImageKHR' (especially if I moved my mouse across the open Sober window), and the window would remain open until I closed it manually.

Thanks!

[2.637.0.730_20240815T074738Z_Player_89789_last.log](https://github.com/user-attachments/files/16622821/2.637.0.730_20240815T074738Z_Player_89789_last.log)

### Graphics Info

`lspci -k | grep -EA3 'VGA|3D|Display'`
```
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
        DeviceName: Intel Kabylake UHD Graphics ULT GT2
        Subsystem: Hewlett-Packard Company Device 84bf
        Kernel driver in use: i915
--
01:00.0 3D controller: NVIDIA Corporation GP108M [GeForce MX150] (rev a1)
        DeviceName: NVIDIA GeForce GTX MX150
        Subsystem: Hewlett-Packard Company Device 84bf
        Kernel driver in use: nvidia

```

`inxi -Gxz`
```
Graphics:
  Device-1: Intel UHD Graphics 620 vendor: Hewlett-Packard driver: i915
    v: kernel arch: Gen-9.5 bus-ID: 00:02.0
  Device-2: NVIDIA GP108M [GeForce MX150] vendor: Hewlett-Packard
    driver: nvidia v: 555.58.02 arch: Maxwell bus-ID: 01:00.0
  Device-3: Quanta HP Wide Vision HD Camera driver: uvcvideo type: USB
    bus-ID: 1-3:3
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.2
    compositor: kwin_wayland driver: X: loaded: intel,nvidia
    unloaded: modesetting dri: i965 gpu: i915,nvidia resolution: 1: 1600x900
    2: 1600x900
  API: EGL v: 1.5 drivers: iris,kms_swrast,nvidia,swrast platforms:
    active: gbm,wayland,x11,surfaceless,device inactive: device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: intel mesa v: 24.1.5-arch1.2
    glx-v: 1.4 direct-render: yes renderer: Mesa Intel UHD Graphics 620 (KBL
    GT2)
  API: Vulkan v: 1.3.279 drivers: nvidia surfaces: xcb,xlib devices: 1
```
