### ISSUE TITLE
Show previous commits for the "sober" flatpak repository.

### ISSUE THREAD

**Issue by xeonxlip** [vinegarhq/sober#161]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Is your feature request related to a problem?

Due to the recent mouse locking issues on 0.0.0-e940d63, I tried to go back to a previous commit (0.0.0-ff1265d) but I only see the latest commit.

### Describe the Solution you'd Like

If you could leave the last or last 2 commits in the repository for users to rollback to a "stable"(ish) version, that would be awesome!

### Describe Alternatives you've considered

I've attempted to "find" the last commit version so I could roll back to that, but no dice.

### Additional context

terminal output: 

```
flatpak remote-info --log sober org.vinegarhq.Sober

Sober - Runtime for Roblox on Linux

        ID: org.vinegarhq.Sober
       Ref: app/org.vinegarhq.Sober/x86_64/master
      Arch: x86_64
    Branch: master
   Version: 0.0.0-e940d63
   License: LicenseRef-proprietary=https://sober.vinegarhq.org/notice.txt
Collection: 
  Download: 2.0 MB
 Installed: 5.2 MB
   Runtime: org.gnome.Platform/x86_64/46
       Sdk: org.gnome.Sdk/x86_64/46

    Commit: e56575916a5a5b72399cee1599f79e731dd2ffe0e5dfd38f7b48980b4d43e6b2
   Subject: Export org.vinegarhq.Sober
      Date: 2024-08-24 14:10:48 +0000
   History: 
```
